<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
        One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    </PropertyGroup>

    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.1.0" />
        <PackageReference Include="SkiaSharp" Version="4.150.1" />
        <PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
        <PackageReference Include="YoutubeExplode.Converter" Version="6.6.0" />
    </ItemGroup>

    <!--<ItemGroup>
        <None Update="bin/Debug/net8.0/ffmpeg\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>-->

    <ItemGroup>
        <None Update="ffmpeg/ffmpeg">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


    <ItemGroup>
        <ProjectReference Include="..\YoutubeToMp4\YoutubeToMp4.csproj" />
    </ItemGroup>
</Project>
